## Mark Shust's Docker Configuration for Magento
## Version 52.1.0
## Target architecture: x86_64 / amd64
## Search engine: Elasticsearch 7

x-amd64-platform: &amd64-platform linux/amd64

services:
  app:
    image: markoshust/magento-nginx:1.28-0
    platform: *amd64-platform
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    image: markoshust/magento-php:8.3-fpm-7
    platform: *amd64-platform
    volumes: *appvolumes
    env_file: env/phpfpm.env

  phpfpm-xdebug:
    image: markoshust/magento-php:8.3-fpm-xdebug-7
    platform: *amd64-platform
    volumes: *appvolumes
    env_file: env/phpfpm.env

  db:
    image: mariadb:10.4.3
    platform: *amd64-platform
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
      --log_bin_trust_function_creators=1
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: valkey/valkey:8.1-alpine
    platform: *amd64-platform
    ports:
      - "6379:6379"

  elasticsearch:
    image: markoshust/magento-elasticsearch:7.17-1
    platform: *amd64-platform
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file: env/elasticsearch.env
    environment:
      - "discovery.type=single-node"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
      - "xpack.security.enabled=false"
      # If Elasticsearch fails due to memory, uncomment this line:
      # - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  rabbitmq:
    image: markoshust/magento-rabbitmq:4.2-0
    platform: *amd64-platform
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env

  mailcatcher:
    image: sj26/mailcatcher:v0.10.0
    platform: *amd64-platform
    ports:
      - "1080:1080"

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
